name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Define image tag
        id: define-tag
        run: |
            if [[ "${{ github.ref_name }}" == "develop" ]]; then
                tag='latest'
            else
                tag='${{ github.sha }}'
            fi
            echo "tag=${tag}" >> $GITHUB_OUTPUT
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: neonlabsorg/neon_test_programs:${{ steps.define-tag.outputs.tag }}
          labels: neonlabsorg/neon_test_programs:${{ steps.define-tag.outputs.tag }}
